### ISSUE TITLE
Cannot read property 'hasOwnProperty' of undefined

### ISSUE THREAD

**Issue by otisg** [sematext/spm-metrics-js#3]
Reported by a user:

```
UnCaught exception: TypeError: Cannot read property 'hasOwnProperty' of undefined
    at CustomMetric.save (/Users/xxx/Projects/yyy/api/node_modules/spm-metrics-js/lib/customMetric.js:61:10)
    at Timeout._repeat (/Users/xxx/Projects/yyy/api/node_modules/spm-metrics-js/lib/customMetric.js:27:12)
    at Timeout.wrapper [as _onTimeout] (timers.js:421:11)
    at Timer.unrefdHandle (timers.js:458:14)","timestamp":"2016-09-14T14:34:45.384Z"}

```

**Comment by megastef** [comment]
Closed by https://github.com/sematext/spm-metrics-js/commit/6c33a056f7b5c06b8ecd73dc4fa61f69a9c4495d (sorry commit message had wrong issue number).
